version: "3.9"
   
services:
  django_gunicorn:
    build:
      context: .
    env_file:
      - server/DACOS/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    restart: always
    