version: "3.9"
   
services:
  django_gunicorn:
    build:
      context: .
    env_file:
      - server/DACOS/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
    