# Generated by Django 3.1.6 on 2021-02-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
