# Generated by Django 3.1.6 on 2021-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210209_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='public_rsa_e',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='public_rsa_n',
            field=models.CharField(max_length=300),
        ),
    ]
