# Generated by Django 3.1.6 on 2021-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='g_in_big_power',
            field=models.CharField(max_length=300),
        ),
    ]
