# Generated by Django 3.1.6 on 2021-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210214_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameRSA', models.CharField(max_length=300)),
                ('usernameAES', models.CharField(max_length=300)),
            ],
        ),
    ]
